name: dotnet package

on:
  push:
    branches: [ "main", "feature" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore src/DecoratorLab3/
    - name: Build
      run: dotnet build src/DecoratorLab3/ --no-restore
    - name: Test
      run: dotnet test src/TestDecoratorLab3/ --no-build --verbosity normal
